services:

  db:
    image: postgres:latest
    container_name: asilo_db
    environment:
      POSTGRES_DB: asilo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  backend:
      build:
        context: ./back
      ports:
        - "8080:8080"
      environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PASS=root
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/asilo
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
      depends_on:
        - db